### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by LeeDr** [scotchfield/elasticsearch-react-example#2]
Any idea what's wrong here?  I did `npm install`, `webpack`, and also tried `npm install navigator` but still getting this;

```
$ node index.js
C:\git\elasticsearch-react-example\index.js:40640
        var asyncDefault = !(navigator && /PhantomJS/i.test(navigator.userAgent));
                             ^

ReferenceError: navigator is not defined
    at Object.module.exports (C:\git\elasticsearch-react-example\index.js:40640:23)
    at __webpack_require__ (C:\git\elasticsearch-react-example\index.js:20:30)
    at Object.module.exports (C:\git\elasticsearch-react-example\index.js:40599:9)
    at __webpack_require__ (C:\git\elasticsearch-react-example\index.js:20:30)
    at Object.<anonymous> (C:\git\elasticsearch-react-example\index.js:40259:37)
    at Object.<anonymous> (C:\git\elasticsearch-react-example\index.js:40546:31)
    at __webpack_require__ (C:\git\elasticsearch-react-example\index.js:20:30)
    at Object.<anonymous> (C:\git\elasticsearch-react-example\index.js:20051:10)
    at Object.<anonymous> (C:\git\elasticsearch-react-example\index.js:20394:31)
    at __webpack_require__ (C:\git\elasticsearch-react-example\index.js:20:30)
```

**Comment by LeeDr** [comment]
I found this which seems like it might be relevant but not sure how to implement it as a fix in this case;

https://stackoverflow.com/questions/37078882/mocha-chai-throws-navigator-not-defined-due-to-react-router-component

**Comment by LeeDr** [comment]
OK, supposed to open index.html in the browser, but then I still get;

```
Uncaught TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'(…)
(anonymous function) @ index.js:66
(anonymous function) @ index.js:128
__webpack_require__ @ index.js:20
(anonymous function) @ index.js:40
(anonymous function) @ index.js:43
```

**Comment by scotchfield** [comment]
That's weird, I haven't seen that! Can you try running `npm start` and see if the error still shows up?

**Comment by LeeDr** [comment]
yep, `npm start` works.  Thanks.
